services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    container_name: f1_api
    build: .
    environment:
      PORT: ${PORT}
      HOST_DB: ${HOST_DB}
      PORT_DB: ${PORT_DB}
      USERNAME_DB: ${USERNAME_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      DATABASE_DB: ${DATABASE_DB}
      SECRET_KEY: ${SECRET_KEY}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '3333:3333'
    depends_on:
      - db

volumes:
  db:

